# Generated by Django 3.2 on 2021-04-29 06:49.

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='姓名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('phone', models.CharField(max_length=20, null=True, verbose_name='手机')),
                ('email', models.CharField(max_length=64, null=True, verbose_name='邮箱')),
                ('limit', models.BooleanField(verbose_name='权限')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='TeacherCases',
            fields=[
                ('caseid', models.AutoField(primary_key=True, serialize=False)),
                ('caseName', models.CharField(max_length=100, verbose_name='用例名称')),
                ('casePre', models.CharField(max_length=100, verbose_name='前置条件')),
                ('caseStep', models.CharField(max_length=200, verbose_name='步骤')),
                ('caseResult', models.CharField(max_length=200, verbose_name='预期结果')),
                ('needid', models.IntegerField(verbose_name='需求id')),
                ('tag', models.CharField(choices=[('teacher', '教师端'), ('student', '学生端'), ('principal', '校区运营系统'), ('question', '题库'), ('learn', '学习系统'), ('rest', '其他')], max_length=100, verbose_name='标签')),
                ('grade', models.CharField(choices=[('high', '高'), ('middle', '中'), ('low', '低')], max_length=100, verbose_name='等级')),
                ('update', models.DateTimeField(default=datetime.datetime(2021, 4, 29, 6, 49, 18, 891824, tzinfo=utc), verbose_name='最后更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caseManage.users', verbose_name='用户名')),
            ],
            options={
                'db_table': 'teachercases',
            },
        ),
        migrations.CreateModel(
            name='StudentCases',
            fields=[
                ('caseid', models.AutoField(primary_key=True, serialize=False)),
                ('caseName', models.CharField(max_length=100, verbose_name='用例名称')),
                ('casePre', models.CharField(max_length=100, verbose_name='前置条件')),
                ('caseStep', models.CharField(max_length=200, verbose_name='步骤')),
                ('caseResult', models.CharField(max_length=200, verbose_name='预期结果')),
                ('needid', models.IntegerField(verbose_name='需求id')),
                ('tag', models.CharField(choices=[('teacher', '教师端'), ('student', '学生端'), ('principal', '校区运营系统'), ('question', '题库'), ('learn', '学习系统'), ('rest', '其他')], max_length=100, verbose_name='标签')),
                ('grade', models.CharField(choices=[('high', '高'), ('middle', '中'), ('low', '低')], max_length=100, verbose_name='等级')),
                ('update', models.DateTimeField(default=datetime.datetime(2021, 4, 29, 6, 49, 18, 892374, tzinfo=utc), verbose_name='最后更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caseManage.users', verbose_name='用户名')),
            ],
            options={
                'db_table': 'studentcases',
            },
        ),
        migrations.CreateModel(
            name='QuestioCases',
            fields=[
                ('caseid', models.AutoField(primary_key=True, serialize=False)),
                ('caseName', models.CharField(max_length=100, verbose_name='用例名称')),
                ('casePre', models.CharField(max_length=100, verbose_name='前置条件')),
                ('caseStep', models.CharField(max_length=200, verbose_name='步骤')),
                ('caseResult', models.CharField(max_length=200, verbose_name='预期结果')),
                ('needid', models.IntegerField(verbose_name='需求id')),
                ('tag', models.CharField(choices=[('teacher', '教师端'), ('student', '学生端'), ('principal', '校区运营系统'), ('question', '题库'), ('learn', '学习系统'), ('rest', '其他')], max_length=100, verbose_name='标签')),
                ('grade', models.CharField(choices=[('high', '高'), ('middle', '中'), ('low', '低')], max_length=100, verbose_name='等级')),
                ('update', models.DateTimeField(default=datetime.datetime(2021, 4, 29, 6, 49, 18, 893552, tzinfo=utc), verbose_name='最后更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caseManage.users', verbose_name='用户名')),
            ],
            options={
                'db_table': 'questioncases',
            },
        ),
        migrations.CreateModel(
            name='PrincipalCases',
            fields=[
                ('caseid', models.AutoField(primary_key=True, serialize=False)),
                ('caseName', models.CharField(max_length=100, verbose_name='用例名称')),
                ('casePre', models.CharField(max_length=100, verbose_name='前置条件')),
                ('caseStep', models.CharField(max_length=200, verbose_name='步骤')),
                ('caseResult', models.CharField(max_length=200, verbose_name='预期结果')),
                ('needid', models.IntegerField(verbose_name='需求id')),
                ('tag', models.CharField(choices=[('teacher', '教师端'), ('student', '学生端'), ('principal', '校区运营系统'), ('question', '题库'), ('learn', '学习系统'), ('rest', '其他')], max_length=100, verbose_name='标签')),
                ('grade', models.CharField(choices=[('high', '高'), ('middle', '中'), ('low', '低')], max_length=100, verbose_name='等级')),
                ('update', models.DateTimeField(default=datetime.datetime(2021, 4, 29, 6, 49, 18, 894101, tzinfo=utc), verbose_name='最后更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caseManage.users', verbose_name='用户名')),
            ],
            options={
                'db_table': 'principalcases',
            },
        ),
        migrations.CreateModel(
            name='OtherCases',
            fields=[
                ('caseid', models.AutoField(primary_key=True, serialize=False)),
                ('caseName', models.CharField(max_length=100, verbose_name='用例名称')),
                ('casePre', models.CharField(max_length=100, verbose_name='前置条件')),
                ('caseStep', models.CharField(max_length=200, verbose_name='步骤')),
                ('caseResult', models.CharField(max_length=200, verbose_name='预期结果')),
                ('needid', models.IntegerField(verbose_name='需求id')),
                ('tag', models.CharField(choices=[('teacher', '教师端'), ('student', '学生端'), ('principal', '校区运营系统'), ('question', '题库'), ('learn', '学习系统'), ('rest', '其他')], max_length=100, verbose_name='标签')),
                ('grade', models.CharField(choices=[('high', '高'), ('middle', '中'), ('low', '低')], max_length=100, verbose_name='等级')),
                ('update', models.DateTimeField(default=datetime.datetime(2021, 4, 29, 6, 49, 18, 891200, tzinfo=utc), verbose_name='最后更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caseManage.users', verbose_name='用户名')),
            ],
            options={
                'db_table': 'othercases',
            },
        ),
        migrations.CreateModel(
            name='LearnCases',
            fields=[
                ('caseid', models.AutoField(primary_key=True, serialize=False)),
                ('caseName', models.CharField(max_length=100, verbose_name='用例名称')),
                ('casePre', models.CharField(max_length=100, verbose_name='前置条件')),
                ('caseStep', models.CharField(max_length=200, verbose_name='步骤')),
                ('caseResult', models.CharField(max_length=200, verbose_name='预期结果')),
                ('needid', models.IntegerField(verbose_name='需求id')),
                ('tag', models.CharField(choices=[('teacher', '教师端'), ('student', '学生端'), ('principal', '校区运营系统'), ('question', '题库'), ('learn', '学习系统'), ('rest', '其他')], max_length=100, verbose_name='标签')),
                ('grade', models.CharField(choices=[('high', '高'), ('middle', '中'), ('low', '低')], max_length=100, verbose_name='等级')),
                ('update', models.DateTimeField(default=datetime.datetime(2021, 4, 29, 6, 49, 18, 892991, tzinfo=utc), verbose_name='最后更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caseManage.users', verbose_name='用户名')),
            ],
            options={
                'db_table': 'learncases',
            },
        ),
        migrations.CreateModel(
            name='CaseFiles',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=100, verbose_name='文件名')),
                ('filepath', models.CharField(max_length=200, verbose_name='文件路径')),
                ('update', models.DateTimeField(default=datetime.datetime(2021, 4, 29, 6, 49, 18, 894573, tzinfo=utc), verbose_name='最后更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caseManage.users', verbose_name='用户名')),
            ],
            options={
                'db_table': 'casefiles',
            },
        ),
    ]
