# Generated by Django 3.2 on 2021-04-29 06:52.

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('caseManage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casefiles',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 29, 6, 52, 38, 673228, tzinfo=utc), verbose_name='最后更新时间'),
        ),
        migrations.AlterField(
            model_name='learncases',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 29, 6, 52, 38, 671854, tzinfo=utc), verbose_name='最后更新时间'),
        ),
        migrations.AlterField(
            model_name='othercases',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 29, 6, 52, 38, 670325, tzinfo=utc), verbose_name='最后更新时间'),
        ),
        migrations.AlterField(
            model_name='principalcases',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 29, 6, 52, 38, 672824, tzinfo=utc), verbose_name='最后更新时间'),
        ),
        migrations.AlterField(
            model_name='questiocases',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 29, 6, 52, 38, 672288, tzinfo=utc), verbose_name='最后更新时间'),
        ),
        migrations.AlterField(
            model_name='studentcases',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 29, 6, 52, 38, 671367, tzinfo=utc), verbose_name='最后更新时间'),
        ),
        migrations.AlterField(
            model_name='teachercases',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 29, 6, 52, 38, 670926, tzinfo=utc), verbose_name='最后更新时间'),
        ),
    ]
